### ISSUE TITLE
What about a stable version?

### ISSUE THREAD

**Issue by iperminov** [LucidWorks/silk#1]
Hi,

Is the current version (as commited in e387fbf8ace1a52db003fae626571c3cd6f46281) stable enough? If not, when are you going to release the stable one?

Best regards,
Igor

**Comment by athana** [comment]
Hi Igor,

I believe the current version is stable enough for general use, but it might need more testing before being production-ready. If you find any bugs, please report the issues or submit pull requests for the fix.

Best Regards,
Andrew
