### ISSUE TITLE
Solr instance is not running in SolrCloud mode.

### ISSUE THREAD

**Issue by jdrews** [LucidWorks/silk#4]
Can Silk work with Solr 5 that is not running in SolrCloud mode? 

Getting this response while trying to load Silk at port 5601. (in Chrome Developer Tools Console)

```
kibana index check
angular.js:8632 GET http://10.16.1.110:5601/solr/solr/admin/collections?action=LIST&wt=json 400 (Bad Request)
```

Then looking up that url in Chrome I get this response:

```
{"responseHeader":{"status":400,"QTime":1},"error":{"msg":"Solr instance is not running in SolrCloud mode.","code":400}}
```

**Comment by athana** [comment]
@jdrews Currently Silk only support SolrCloud mode. You can run SolrCloud with a single node of Solr.

**Comment by jdrews** [comment]
Thanks @athana. Closing issue.
